var searchData=
[
  ['baseclient',['BaseClient',['../classofx_1_1_h_t_t_p_1_1_form_request.html#a498ee2d3956063638f281708e5aff4af',1,'ofx::HTTP::FormRequest']]],
  ['baseconnection_5f',['BaseConnection_',['../classofx_1_1_h_t_t_p_1_1_base_connection__.html',1,'ofx::HTTP::BaseConnection_&lt; RouteType, FrameType &gt;'],['../classofx_1_1_h_t_t_p_1_1_base_connection__.html#a3a0f3f6317106a2ddf4af7b1d17324a9',1,'ofx::HTTP::BaseConnection_::BaseConnection_()']]],
  ['baseposteventargs',['BasePostEventArgs',['../classofx_1_1_h_t_t_p_1_1_base_post_event_args.html',1,'ofx::HTTP::BasePostEventArgs'],['../classofx_1_1_h_t_t_p_1_1_base_post_event_args.html#ac48601dde76c61114514121455744456',1,'ofx::HTTP::BasePostEventArgs::BasePostEventArgs()']]],
  ['baseroute_5f',['BaseRoute_',['../classofx_1_1_h_t_t_p_1_1_base_route__.html',1,'ofx::HTTP::BaseRoute_&lt; SettingsType &gt;'],['../classofx_1_1_h_t_t_p_1_1_base_route__.html#a29c3a33e3b1e67db352451908566889c',1,'ofx::HTTP::BaseRoute_::BaseRoute_()']]],
  ['baseroute_5f_3c_20baseroutesettings_20_3e',['BaseRoute_&lt; BaseRouteSettings &gt;',['../classofx_1_1_h_t_t_p_1_1_base_route__.html',1,'ofx::HTTP']]],
  ['baseroute_5f_3c_20filesystemroutesettings_20_3e',['BaseRoute_&lt; FileSystemRouteSettings &gt;',['../classofx_1_1_h_t_t_p_1_1_base_route__.html',1,'ofx::HTTP']]],
  ['baseroute_5f_3c_20ipvideoroutesettings_20_3e',['BaseRoute_&lt; IPVideoRouteSettings &gt;',['../classofx_1_1_h_t_t_p_1_1_base_route__.html',1,'ofx::HTTP']]],
  ['baseroute_5f_3c_20postroutesettings_20_3e',['BaseRoute_&lt; PostRouteSettings &gt;',['../classofx_1_1_h_t_t_p_1_1_base_route__.html',1,'ofx::HTTP']]],
  ['baseroute_5f_3c_20sseroutesettings_20_3e',['BaseRoute_&lt; SSERouteSettings &gt;',['../classofx_1_1_h_t_t_p_1_1_base_route__.html',1,'ofx::HTTP']]],
  ['baseroute_5f_3c_20websocketroutesettings_20_3e',['BaseRoute_&lt; WebSocketRouteSettings &gt;',['../classofx_1_1_h_t_t_p_1_1_base_route__.html',1,'ofx::HTTP']]],
  ['baseroutehandler_5f',['BaseRouteHandler_',['../classofx_1_1_h_t_t_p_1_1_base_route_handler__.html',1,'ofx::HTTP::BaseRouteHandler_&lt; RouteType &gt;'],['../classofx_1_1_h_t_t_p_1_1_base_route_handler__.html#a9352f997b2a87aff98183e9edf34abbe',1,'ofx::HTTP::BaseRouteHandler_::BaseRouteHandler_()']]],
  ['baseroutehandler_5f_3c_20ipvideoroute_20_3e',['BaseRouteHandler_&lt; IPVideoRoute &gt;',['../classofx_1_1_h_t_t_p_1_1_base_route_handler__.html',1,'ofx::HTTP']]],
  ['baseroutehandler_5f_3c_20postroute_20_3e',['BaseRouteHandler_&lt; PostRoute &gt;',['../classofx_1_1_h_t_t_p_1_1_base_route_handler__.html',1,'ofx::HTTP']]],
  ['baseroutehandler_5f_3c_20sseroute_20_3e',['BaseRouteHandler_&lt; SSERoute &gt;',['../classofx_1_1_h_t_t_p_1_1_base_route_handler__.html',1,'ofx::HTTP']]],
  ['baseroutehandler_5f_3c_20websocketroute_20_3e',['BaseRouteHandler_&lt; WebSocketRoute &gt;',['../classofx_1_1_h_t_t_p_1_1_base_route_handler__.html',1,'ofx::HTTP']]],
  ['baseroutesettings',['BaseRouteSettings',['../classofx_1_1_h_t_t_p_1_1_base_route_settings.html',1,'ofx::HTTP::BaseRouteSettings'],['../classofx_1_1_h_t_t_p_1_1_base_route_settings.html#ae150773327dceb68573f4fa14507c664',1,'ofx::HTTP::BaseRouteSettings::BaseRouteSettings()']]],
  ['baseserver_5f',['BaseServer_',['../classofx_1_1_h_t_t_p_1_1_base_server__.html',1,'ofx::HTTP']]],
  ['baseserver_5f_3c_20simplefileserversettings_2c_20simplesessionstore_20_3e',['BaseServer_&lt; SimpleFileServerSettings, SimpleSessionStore &gt;',['../classofx_1_1_h_t_t_p_1_1_base_server__.html',1,'ofx::HTTP']]],
  ['baseserver_5f_3c_20simpleipvideoserversettings_2c_20simplesessionstore_20_3e',['BaseServer_&lt; SimpleIPVideoServerSettings, SimpleSessionStore &gt;',['../classofx_1_1_h_t_t_p_1_1_base_server__.html',1,'ofx::HTTP']]],
  ['baseserver_5f_3c_20simplepostserversettings_2c_20simplesessionstore_20_3e',['BaseServer_&lt; SimplePostServerSettings, SimpleSessionStore &gt;',['../classofx_1_1_h_t_t_p_1_1_base_server__.html',1,'ofx::HTTP']]],
  ['baseserver_5f_3c_20simplesseserversettings_2c_20simplesessionstore_20_3e',['BaseServer_&lt; SimpleSSEServerSettings, SimpleSessionStore &gt;',['../classofx_1_1_h_t_t_p_1_1_base_server__.html',1,'ofx::HTTP']]],
  ['baseserver_5f_3c_20simplewebsocketserversettings_2c_20simplesessionstore_20_3e',['BaseServer_&lt; SimpleWebSocketServerSettings, SimpleSessionStore &gt;',['../classofx_1_1_h_t_t_p_1_1_base_server__.html',1,'ofx::HTTP']]],
  ['baseserverhandle',['BaseServerHandle',['../classofx_1_1_h_t_t_p_1_1_base_server_handle.html',1,'ofx::HTTP']]],
  ['baseserversettings',['BaseServerSettings',['../classofx_1_1_h_t_t_p_1_1_base_server_settings.html',1,'ofx::HTTP']]],
  ['basesession',['BaseSession',['../classofx_1_1_h_t_t_p_1_1_base_session.html',1,'ofx::HTTP']]],
  ['basesessionstore',['BaseSessionStore',['../classofx_1_1_h_t_t_p_1_1_base_session_store.html',1,'ofx::HTTP']]],
  ['broadcast',['broadcast',['../classofx_1_1_h_t_t_p_1_1_web_socket_route.html#a1186f68185105c58a6156660bbe1e9d4',1,'ofx::HTTP::WebSocketRoute']]],
  ['buffer',['buffer',['../classofx_1_1_h_t_t_p_1_1_response.html#a2e91953e91fcb59a88b5d58128ec5540',1,'ofx::HTTP::Response']]],
  ['bufferresponsehandler',['BufferResponseHandler',['../classofx_1_1_h_t_t_p_1_1_buffer_response_handler.html',1,'ofx::HTTP']]],
  ['bytebuffer',['byteBuffer',['../classofx_1_1_h_t_t_p_1_1_response.html#aa95b45d8196aff7985b5a47082a32d05',1,'ofx::HTTP::Response']]],
  ['bytes_5funit',['BYTES_UNIT',['../classofx_1_1_h_t_t_p_1_1_response.html#a8aa0c23cbf2ab41cafce2555dbe077b9',1,'ofx::HTTP::Response']]],
  ['bytespersecond',['bytesPerSecond',['../classofx_1_1_h_t_t_p_1_1_progress.html#ada627b9573368a823a29271574c4f3d8',1,'ofx::HTTP::Progress']]]
];
